apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: pcb_factory
      defaultBucket: defect_metrics
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true
