# telegraf/telegraf.conf
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "pcb_edge_node"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "pcb_factory"
  bucket = "defect_metrics"

[[inputs.opcua]]
  name = "pcb_defect_metrics"
  endpoint = "opc.tcp://backend:4840/freeopcua/server/"
  connect_timeout = "10s"
  request_timeout = "5s"
  security_policy = "None"
  security_mode = "None"
  auth_method = "UserName"
  username = "$OPCUA_USER"
  password = "$OPCUA_PASSWORD"

  [[inputs.opcua.nodes]]
    name = "Total_PCBs_Processed"
    namespace = "2"
    identifier_type = "s"
    identifier = "Total_PCBs_Processed"

  [[inputs.opcua.nodes]]
    name = "Total_Defective_PCBs"
    namespace = "2"
    identifier_type = "s"
    identifier = "Total_Defective_PCBs"

  [[inputs.opcua.nodes]]
    name = "Last_Defect_Type"
    namespace = "2"
    identifier_type = "s"
    identifier = "Last_Defect_Type"
